"""added_email_notifications_and_verification

Revision ID: 4014f6924aa1
Revises: b9bb9d89731e
Create Date: 2026-06-02 20:56:53.350471

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4014f6924aa1"
down_revision: Union[str, Sequence[str], None] = "b9bb9d89731e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("template_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_notifications_recipient"), "email_notifications", ["recipient"], unique=False)
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))

    # 3. Проставляем дефолтное значение False (или True) для ВСЕХ существующих записей
    op.execute("UPDATE users SET is_verified = False WHERE is_verified IS NULL")

    # 4. Теперь, когда пустых ячеек не осталось, смело накатываем NOT NULL
    op.alter_column("users", "is_verified", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_index(op.f("ix_email_notifications_recipient"), table_name="email_notifications")
    op.drop_table("email_notifications")
    # ### end Alembic commands ###
