"""make user_id nullable in generation_process

Revision ID: 49d94700fdc1
Revises: f435aa8157f5
Create Date: 2026-06-05 22:14:36.332004

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49d94700fdc1"
down_revision: Union[str, Sequence[str], None] = "f435aa8157f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("generation_processes", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("generation_processes", "user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
