"""add cascade delete to refresh sessions

Revision ID: 5a241cec2b57
Revises: 65c36c590ee5
Create Date: 2026-05-10 17:03:29.671115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a241cec2b57'
down_revision: Union[str, Sequence[str], None] = '65c36c590ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_constraint(op.f('refresh_sessions_user_id_fkey'), 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_sessions_user_id_fkey'), 'refresh_sessions', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.alter_column('refresh_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
