"""file_path_nullable

Revision ID: b9bb9d89731e
Revises: 07af7b470ed3
Create Date: 2026-05-14 15:45:33.438627

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9bb9d89731e"
down_revision: Union[str, Sequence[str], None] = "07af7b470ed3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_templates", "file_path", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_templates", "file_path", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
