"""cascade delete email_notifications

Revision ID: f435aa8157f5
Revises: 4014f6924aa1
Create Date: 2026-06-05 15:43:45.042460

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f435aa8157f5"
down_revision: Union[str, Sequence[str], None] = "4014f6924aa1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("email_notifications_user_id_fkey"), "email_notifications", type_="foreignkey")
    op.create_foreign_key(None, "email_notifications", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "email_notifications", type_="foreignkey")
    op.create_foreign_key(op.f("email_notifications_user_id_fkey"), "email_notifications", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
