"""again_fix_updated_at_onupdate

Revision ID: f70f93a32596
Revises: f7dd10b4f559
Create Date: 2026-04-27 16:36:03.315938

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f70f93a32596"
down_revision: Union[str, Sequence[str], None] = "f7dd10b4f559"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
