name: Deploy to Cloud.ru

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_URI }}
          username: ${{ secrets.CR_LOGIN }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.CR_URI }}/digitalizer-backend:latest
